[package]
name = "lattice_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
amqprs = "1.4.0"
automerge = "0.4.1"
automerge-persistent-sled = "0.4.0"
autosurgeon = "0.7.1"
graphql-parser = "0.4.0"
rusqlite = "0.29.0"
tokio = "1.28.2"
